<?php

declare(strict_types=1);

namespace CommonSight\Infrastructure\Contract;

/**
 * Joins the catalog terms of the core and of the plugins (concept: sources as plugins, V14, V17): checks every entry,
 * rejects a term contributed twice, and derives the catalog for the frontend, the schema definitions and the overview
 * of all terms. Works on decoded JSON; reading and writing the files is up to the build script.
 */
final class CatalogBuilder
{
    /** Lists of the catalog with their schema definition name and the extra fields their entries need. */
    private const LISTS = [
        'measuredQuantities' => ['measuredQuantity', []],
        'modelQuantities' => ['modelQuantity', ['decimals', 'shortSuffix']],
        'warningCategories' => ['warningCategory', []],
        'newsCategories' => ['newsCategory', []],
        'newsFeeds' => ['newsFeed', ['country']],
    ];

    /**
     * @param array<mixed> $core decoded contract/catalog/builtin.json
     * @param array<array<mixed>> $plugins decoded catalog.json per plugin id
     * @return array<string, list<array<mixed>>> list -> entries with "contributedBy"
     * @throws \RuntimeException listing every problem
     */
    public function join(array $core, array $plugins): array
    {
        [$entries, $problems] = $this->entries(['core' => $core] + $plugins);
        $catalog = array_fill_keys(array_keys(self::LISTS), []);
        $owners = [];
        foreach ($entries as [$contributor, $list, $entry]) {
            $id = is_array($entry) && is_string($entry['id'] ?? null) ? $entry['id'] : '?';
            $problem = $this->problemOf($list, $entry) ?? (isset($owners[$list][$id]) ? 'already contributed by ' . $owners[$list][$id] : null);
            if ($problem !== null) {
                $problems[] = sprintf('%s: %s "%s": %s', $contributor, $list, $id, $problem);
                continue;
            }
            $owners[$list][$id] = $contributor;
            $catalog[$list][] = ['id' => $id] + (array) $entry + ['contributedBy' => $contributor];
        }
        if ($problems !== []) {
            throw new \RuntimeException("Invalid catalog terms:\n  " . implode("\n  ", $problems));
        }

        return $catalog;
    }

    /**
     * All entries of all contributions in order, and the lists that are not known.
     *
     * @param array<array<mixed>> $contributions by contributor
     * @return array{list<array{string, string, mixed}>, list<string>}
     */
    private function entries(array $contributions): array
    {
        $entries = [];
        $problems = [];
        foreach ($contributions as $contributor => $contribution) {
            foreach ($contribution as $list => $listEntries) {
                if ($list === '$comment') {
                    continue;
                }
                if (!isset(self::LISTS[$list]) || !is_array($listEntries)) {
                    $problems[] = sprintf('%s: unknown catalog list "%s"', $contributor, $list);
                    continue;
                }
                foreach ($listEntries as $entry) {
                    $entries[] = [(string) $contributor, $list, $entry];
                }
            }
        }

        return [$entries, $problems];
    }

    /**
     * @param array<string, list<array<mixed>>> $catalog
     * @return array<string, mixed> contract/schema/catalog.schema.json
     */
    public function schema(array $catalog): array
    {
        $defs = [];
        foreach (self::LISTS as $list => [$name]) {
            $defs[$name] = ['type' => 'string', 'enum' => array_map(static fn(array $e): mixed => $e['id'], $catalog[$list])];
        }

        return [
            '$schema' => 'https://json-schema.org/draft/2020-12/schema',
            '$id' => 'https://commonsight.org/schema/v1/catalog.schema.json',
            'title' => 'Catalog',
            'description' => 'Terms contributed by the core and the plugins (V14). Generated by backend/bin/build-contract.php from contract/catalog/builtin.json and plugins/*/*/catalog.json; do not edit by hand.',
            '$defs' => $defs,
        ];
    }

    /** @param array<string, list<array<mixed>>> $catalog */
    public function overview(array $catalog): string
    {
        $lines = ['# Catalog terms', '', 'Generated by `backend/bin/build-contract.php`; do not edit by hand. Check here whether a term exists before contributing a new one (V17).', ''];
        foreach ($catalog as $list => $entries) {
            array_push($lines, '## ' . $list, '', '| Id | Label | Definition | Contributed by |', '|---|---|---|---|');
            foreach ($entries as $entry) {
                $lines[] = sprintf('| `%s` | %s | %s | %s |', ...array_map(static fn(mixed $v): string => is_scalar($v) ? (string) $v : '', [$entry['id'], $entry['label'] ?? '', $entry['definition'] ?? '', $entry['contributedBy'] ?? '']));
            }
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function problemOf(string $list, mixed $entry): ?string
    {
        if (!is_array($entry) || !is_string($entry['id'] ?? null) || preg_match('/^[a-z][A-Za-z0-9-]{0,40}$/', $entry['id']) !== 1) {
            return 'id missing or invalid (lowerCamelCase or kebab-case)';
        }
        foreach (['label', 'definition'] as $field) {
            if (!is_string($entry[$field] ?? null) || trim($entry[$field]) === '') {
                return $field . ' missing';
            }
        }
        foreach (self::LISTS[$list][1] as $field) {
            if (!array_key_exists($field, $entry)) {
                return $field . ' missing';
            }
        }

        return $this->fieldProblem($entry);
    }

    /** @param array<mixed> $entry */
    private function fieldProblem(array $entry): ?string
    {
        if (isset($entry['decimals']) && (!is_int($entry['decimals']) || $entry['decimals'] < 0 || $entry['decimals'] > 4)) {
            return 'decimals must be 0 to 4';
        }
        if (array_key_exists('shortSuffix', $entry) && !is_string($entry['shortSuffix'])) {
            return 'shortSuffix must be text';
        }
        if (isset($entry['country']) && (!is_string($entry['country']) || preg_match('/^[A-Z]{2}$/', $entry['country']) !== 1)) {
            return 'country must be an ISO 3166-1 code like DE';
        }

        return null;
    }
}
