/**
 * Provides the catalog terms of the core and the plugins from contract/catalog (V14): the label of each term, shown
 * verbatim, and its display details. Generated by the backend's contract build; the order of a list is its display order.
 */
import catalogJson from '@contract/catalog/catalog.json';
import type { NewsCategory } from './types';

export interface CatalogEntry {
  id: string;
  label: string;
  definition: string;
  /** "core" or the id of the contributing plugin. */
  contributedBy: string;
}

export interface ModelQuantityEntry extends CatalogEntry {
  decimals: number;
  /** Appended to the rounded value in short form, e.g. "°" on the map. */
  shortSuffix: string;
}

export interface NewsFeedEntry extends CatalogEntry {
  /** Home country of the feed (ISO 3166-1); its feeds come first for that country. */
  country: string;
}

export interface Catalog {
  measuredQuantities: CatalogEntry[];
  modelQuantities: ModelQuantityEntry[];
  warningCategories: CatalogEntry[];
  newsCategories: CatalogEntry[];
  newsFeeds: NewsFeedEntry[];
}

export const catalog = catalogJson as Catalog;

/** News topics in their display order. */
export const NEWS_CATEGORIES: readonly NewsCategory[] = catalog.newsCategories.map(
  (entry) => entry.id as NewsCategory,
);

/** Label of a term; the id itself for a term the bundle does not know yet (data newer than the bundle). */
export function termLabel(list: readonly CatalogEntry[], id: string): string {
  return list.find((entry) => entry.id === id)?.label ?? id;
}

/** Display details of a model quantity; whole numbers without suffix for an unknown one. */
export function modelQuantity(id: string): Pick<ModelQuantityEntry, 'label' | 'decimals' | 'shortSuffix'> {
  return (
    catalog.modelQuantities.find((entry) => entry.id === id) ?? { label: id, decimals: 0, shortSuffix: '' }
  );
}
