/**
 * Loads test snapshots: our own under tests/fixtures/ and, if present, the ones generated by the backend under
 * contract/fixtures/.
 */
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Country, Snapshot, StatusResponse } from '../../src/contract/types';

// As a string, because jsdom brings its own URL class, which fileURLToPath does not accept.
const here = dirname(fileURLToPath(import.meta.url));
export const OWN_FIXTURES = join(here, '..', 'fixtures');
export const CONTRACT_FIXTURES = join(here, '..', '..', '..', 'contract', 'fixtures');
export const SCHEMA_DIR = join(here, '..', '..', '..', 'contract', 'schema');

export interface NamedJson {
  name: string;
  data: unknown;
}

export function readJsonDir(dir: string): NamedJson[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((file) => file.endsWith('.json'))
    .sort()
    .map((file) => ({ name: file, data: JSON.parse(readFileSync(join(dir, file), 'utf8')) as unknown }));
}

/** Our own snapshot fixtures (without status responses). */
export function ownSnapshots(): { name: string; snapshot: Snapshot }[] {
  return readJsonDir(OWN_FIXTURES)
    .filter((entry) => !entry.name.startsWith('status-'))
    .map((entry) => ({ name: entry.name, snapshot: entry.data as Snapshot }));
}

/** Sample snapshots `<layer>-<scope>.json` generated by the backend; empty as long as they do not exist. */
export function contractSnapshots(): { name: string; snapshot: Snapshot }[] {
  return readJsonDir(CONTRACT_FIXTURES)
    .filter((entry) => typeof entry.data === 'object' && entry.data !== null && 'layer' in entry.data)
    .map((entry) => ({ name: entry.name, snapshot: entry.data as Snapshot }));
}

export function snapshot(name: string): Snapshot {
  return JSON.parse(readFileSync(join(OWN_FIXTURES, `${name}.json`), 'utf8')) as Snapshot;
}

export function statusAT(): StatusResponse {
  return JSON.parse(readFileSync(join(OWN_FIXTURES, 'status-AT.json'), 'utf8')) as StatusResponse;
}

/** Status of another country, derived from the Austrian one: country layers with their own scope and path. */
export function statusFor(country: Country): StatusResponse {
  const text = readFileSync(join(OWN_FIXTURES, 'status-AT.json'), 'utf8')
    .replaceAll('"scope": "AT"', `"scope": "${country}"`)
    .replaceAll('/AT/', `/${country}/`);
  return JSON.parse(text) as StatusResponse;
}

/** Snapshot of another country, derived from an Austrian fixture, with its own item IDs. */
export function snapshotFor(name: string, country: Country): Snapshot {
  const base = snapshot(name);
  return {
    ...base,
    scope: country,
    items: base.items.map((item) => ({ ...item, id: `${country}-${item.id}`, regionIds: [] })),
  };
}
