/**
 * Test aids for layer packages (plugins/layers/<id>/frontend/*.test.ts, layers as plugins L5): the formats and texts of the
 * core in German and Europe/Berlin, as the core's own tests use them, and a render context for the map parts. Only
 * tests import this module; it is not part of the element.
 */
import type { LayerId, Snapshot } from '../contract/types';
import { uiFormat } from '../domain/views/ui-format';
import { catalogsFor } from '../i18n/catalogs';
import { createFormats } from '../i18n/formats';
import { createTranslator } from '../i18n/translator';
import type { RenderContext } from '../map/layers/feature-model';
import type { UiFormat } from './ui';

/** The point in time of the core's tests (2026-09-28 12:00 UTC). */
export const TEST_NOW = Date.parse('2026-09-28T12:00:00Z');

const formats = createFormats({ locales: ['de-DE'], timeZone: 'Europe/Berlin' });
const translator = createTranslator({
  ...catalogsFor('de'),
  locale: 'de-DE',
  formatNumber: (value) => formats.number(value),
});

/** Numbers, times and the texts of all packages as the page shows them in German. */
export function testFormat(nowMs: number = TEST_NOW): UiFormat {
  return uiFormat({ t: translator, format: formats, nowMs });
}

export function testRenderContext(layer: LayerId, nowMs: number = TEST_NOW): RenderContext {
  return { layer, layerColor: '#398ed4', labelColor: '#333333', labelHalo: '#ffffff', nowMs };
}

/** A contract fixture (contract/fixtures/<layer>-<scope>.json, generated by the backend) as a snapshot. */
export function asSnapshot(json: unknown): Snapshot {
  return json as Snapshot;
}
